### ISSUE TITLE
Visibility bug for small size

### ISSUE THREAD

**Issue by sharhalakis** [boeledi/flutter_bootstrap#1]
https://github.com/boeledi/flutter_bootstrap/blob/a837fb23b8e7d9ab89aed112884ebd0c579d8610/lib/src/flutter_bootstrap.dart#L623-L628

The Visibility check always sets `_visibilityPerSize['']` because all `col-` sizes start with `col-`. 

It results in all elements being visible for small.

**Comment by boeledi** [comment]
thanks.  Fixed in version 1.0.2
