### ISSUE TITLE
Calculations off by 1px

### ISSUE THREAD

**Issue by gibahjoe** [boeledi/flutter_bootstrap#2]
Hello,

According to your documentation and even bootstrap's the below are the dimensions for devices

- xs for extra small screens < 576px
- sm for small screens > 575px and < 768px
- md for medium screens > 767px and < 992px
- lg for large screens > 991px and < 1200px
- xl for extra large screens > 1199px

However, sm starts from 768 in the library instead of 767.

This was tested on chrome using flutter web.

**Comment by gibahjoe** [comment]
See pr #5

**Comment by boeledi** [comment]
my apologies.
Version 1.0.2 has been published.
